### ISSUE TITLE
Solved: Error: in `start_tag': undefined method `[]' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by JohnBat26** [runefs/maroon#11]
This is my code:

``` ruby
require 'maroon/kernel'
require 'build'

module Demands

  Context.define :DemandProcessing do

    def initialize(demand, requied_organization, params)
      @demand = demand
      @requied_organization = requied_organization
      @params = params
    end

    role :demand do
      def withdraw(amount)
        source.movement(amount)
        source.log 'withdrawal ' + amount.to_s
      end
    end

    role :requied_organization do
      def find_or_create(params)
      #...
     end
    end

   def process
     organization, status = requied_organization.find_or_create(params)
     return status
   end
end

demand = Demand.new
required_organization = Organization.new
ctx = Demands::DemandsProcessing.new(demand, required_organization)
ctx.process
```

And I get next error:
/home/johnbat26/.rvm/gems/ruby-2.0.0-p247@wc/gems/sourcify-0.5.0/lib/sourcify/proc/scanner/dstring.rb:49:in `start_tag': undefined method`[]' for nil:NilClass (NoMethodError)
    from /home/johnbat26/.rvm/gems/ruby-2.0.0-p247@wc/gems/sourcify-0.5.0/lib/sourcify/proc/scanner/dstring.rb:53:in `end_tag'

Why?

**Comment by JohnBat26** [comment]
Promblem resolved.
It was in find_or_create method.
I use other organization_xxx  name and maroon can not find discover it name in roles.
Please, add more useful documentation about gem:
- How properly require gem from other code:
  this don't obvious:

``` ruby
require 'maroon/kernel'
require 'build'
```
- How properly use maroon in Rails and from Rspec and Cucumber?
- Want to see benchmark test in compare to #extend and, alias_dci, schizo etc.
- Want to see many examples at main page from several business cases.

For success work with DCI need shift paradigm in mind, therefore many simple (not mathematics) examples will be very useful

and thanks for your gem! ;)

**Comment by runefs** [comment]
Sorry for the late response but I'm enjoying vacation at the moment. I'll look at your comments when I'm back. one thing to note is that usually when you get the [] not found for nilclass it's because of use of double qoutes (") which is HIGHLY unfortunate but is due to a bug in sourcify (a bug introduced after I started using that gem I believe). In the next version there's a more helpfull error message for that. 

For examples. Have you seen the examples included with the source code? and of course maroon it self is an example too (although highly complex) maroon is written using it self both to field test the gem but also to have a complex example.

for use of the gem there's a few blog posts at http://runefs.com but you are right it would serve the community well if it was easier to find from here.

One of the things that's described at my blog is the difference between 

require 'maroon'

and

require 'maroon/kernel'

the latter adds a method to kernel so you can do

context :my_context

instead of

Context.define :my_context

For benchmarking I did so with an earlier version. I haven't tested it against alias_dci lately (I know the guy who did that gem and help out with it as well as he inspired me). against extend it's a very simple question, since _all_ the "magic" happens at interpretation time and not at runtime maroon beats #extend hands down and alias_dci doesn't use source transformation either. I know alias_dci is faster than #extend but the reason why I chose to do source transformation rather than aliasing methods has to do with the constraints of DCI. alias_Dci is almost true to all of them but misses out on some of them. It might be as fast as maroon but you wouldn't unfortunately be able to do pure DCI. That however might not be a problem if you do not fall into the subtle pits of dark matter.

I haven't tried using it with RSpec nor with Rails (saturnflyer might have tried that but I don't know)

I have been wanting to do some maroon work for a while and perhaps benchmarking and RSpec testing and rails should be the next few things

Thanks for your interest in maroon and do keep me posted on your experiences
